In [1]:
import numpy as np
import random as rd

In [19]:
class Environment():
    
    #fields:
    #a grid ofsize
    def __init__(self, size:int):
        self.size = size
        self.grid, self.a = self.setup_grid(size)
        self.b = (size-1, size-1)

    def setup_grid(self, size):
        field = np.zeros((size,size))
        x, y = rd.randint(0, size-1), rd.randint(0, size-1)
        field[x,y] = 1  #A represented by 1
        field[size-1,size-1] = 2  #B represented by 2
        return field, (x,y)


class Agent():
    def __init__():
        pass
    

class Hypers():
    def __init__(self, eps):
        self.eps = eps

    def __call__(self):
        return self.eps

    

In [30]:
grid = Environment(5)
print(grid.grid)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2.]]
