In [13]:
import numpy as np
import random as rd
import time

In [22]:
class Environment():
    
    #fields:
    #a grid of size defined by parameter
    #b, a tuple repsenting the delivery location
    #a, a tuple representing the package location
    #size, an int representing the horizontal and vertical dimensions of the grid
    def __init__(self, size:int, a = None):
        self.size = size
        self.b = (size-1, size-1)
        self.package = False #boolean determining whether package has been collected
        self.grid, self.a, self.agent = self.setup_grid(size, a)
        #potentially need a rewards directory for grid states:
        #give, say, 50 for (a, agent.collected = 0), and 50 for (a, agent.collected = 1), and -1 for ANY other states
        #make this a dict or a lookup table


    #method to set up the original grid including a location
    def setup_grid(self, size, a):
        grid = np.zeros((size,size))
        #set a location
        if a is None:
            x, y = rd.randint(0, size-1), rd.randint(0, size-1)
            while (x,y) == self.b:
                x, y = rd.randint(0, size-1), rd.randint(0, size-1)
            grid[x,y] = 1  #A represented by 1
        else:
            x, y = a
            grid[x,y] = 1
        #set agent starting location
        agent_x, agent_y = rd.randint(0, size-1), rd.randint(0, size-1)
        while ((agent_x, agent_y) == ((x,y) or self.b)):
            agent_x, agent_y = rd.randint(0, size-1), rd.randint(0, size-1)
        grid[agent_x, agent_y] = -1
        grid[self.b] = 2  #B represented by 2
        return grid, (x,y), (agent_x, agent_y)
    
    def get_state(self):
        return state(self.a, self.b, self.agent, self.package)
    
    # def get_reward_from_state(self, state):
    #     if state == ()# coordinates here for agent getting a or b
    #         return 50
    #     return -1        
    
    #Method which updates the location of the agent on the grid. Currently just zeroes whatever it landed on, setting package collection to true if applicable
    def move_agent(self, direction):
        agent_x, agent_y = self.agent
        self.grid[agent_x, agent_y] = 0
        if direction=="left":
            if agent_x-1 >= 0:
                self.agent = (agent_x - 1, agent_y)
        if direction=="right":
            if agent_x + 1 < self.size:
                self.agent = (agent_x + 1, agent_y)
        if direction=="up":
            if agent_y-1 >= 0:
                self.agent = (agent_x, agent_y - 1)
        if direction=="down":
            if agent_y + 1 < self.size:
                self.agent = (agent_x, agent_y +1)
        self.grid[self.agent] = -1
        if self.agent == self.a:
            self.package = True

@dataclass(frozen=True)
class state:
    a: tuple
    b: tuple
    agent: tuple
    package: bool
    #noot: noot

#q table declared as a dictionary of {state, reward:int}



#An agent class. Currently barebones
class Agent():
    def __init__(self):
        self.q_table = {}
        self.opts = ["up", "down", "left", "right"]

    def choose_best_option():
        #agent acts under policy
        #gets a rewad from the state
        #calls the Update Q table method
        #repeats to end of epoch or task completion
        pass

    def q_table_update(q_table, state, reward):
        pass #I'm kinda high while writing this so I have no idea if this will work 
    #check each possible move that the agent could make - this can actually test the agent's own logic
    #calculate the VALUE of the states of each move
    #update own state as a result based on future rewards - values learned in exploration?
    #this can be a method of the agent maybe
    #Ensure that moves

    def move(self):
        return rd.choice(self.opts)
    
#Class to store hyperparameters
class Hypers():
    def __init__(self, eps, gamma, steps_per_ep):
        self.eps = eps # learning rate
        self.gamma = gamma # discount rate
        self.steps_per_ep = steps_per_ep #steps per episode


## Q Learn Notes

Rewards come from the environment, agent has values on states that it figures out from the rewards that the environment offers it.

Game has multiple episodes (like, tens of thousands).

Episode has multiple (hundreds?) timesteps. At each episode, we'll have a different location of A from all 24 possible states.

Q table learned across all 24 A locations, 25 agent locations, 4 possible actions, and the pre/post plant situation.

So in total 24 * 25 * 2 states, and four possible actions in each state.

4800 state-action space in total for this toy example.

#### SPECULATIVELY;

If we're constructing this Q-table and using the Bellman equation to backpropagate the rewards from end-state into the Q table, we are effectively "learning" a table which tells us what future rewards are going to be in future states. This lets us, in our _current_ state, choose the action which will best be producing future rewards. So our first near empty Q table will have the agent wander around effectively randomly.


Start with a fixed A and fixed B, to see if you CAN actually learn the Q values. Only THEN do we change to a dynamic location of A.

In [24]:
# Demo

hypers = Hypers(
    eps = 1e-3, 
    gamma = 0.1, 
    steps_per_ep = 100
)

import random as rd
grid = Environment(size = 5)
bond = Agent()


for i in range(10):
    grid.move_agent(bond.move())
    print(grid.grid)
    time.sleep(1)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  2.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]


KeyboardInterrupt: 