In [1]:
import numpy as np
import random as rd
import time

In [6]:
class Environment():
    
    #fields:
    #a grid of size defined by parameter
    #b, a tuple repsenting the delivery location
    #a, a tuple representing the package location
    #size, an int representing the horizontal and vertical dimensions of the grid
    def __init__(self, size:int):
        self.size = size
        self.b = (size-1, size-1)
        self.grid, self.a = self.setup_grid(size)
        ## IS THIS WHERE THE AGENT SHOULD BE INITIATED?

    #method to set up the original grid including a location
    def setup_grid(self, size):
        grid = np.zeros((size,size))
        x, y = rd.randint(0, size-1), rd.randint(0, size-1)
        while (x,y) == self.b:
            x, y = rd.randint(0, size-1), rd.randint(0, size-1)
        # x, y = (0,0)
        grid[x,y] = 1  #A represented by 1
        grid[size-1,size-1] = 2  #B represented by 2
        return grid, (x,y)
    
    #method to add start location of agent to grid as well
 #TODO: consider whether to initialise agent as part of environment initialisation
 #pass agent coordinates into constructor instead lmao DENSE
    def set_agent_start(self, agent):
        self.agent_coords = (agent.x, agent.y)
    
    #Method which updates the location of the agent on the grid. Currently just zeroes whatever it landed on - can include other logic instead
    def move_agent(self, agent_move):
        x, y = self.agent_coords
        self.grid[x,y] = 0
        self.agent_coords = agent_move
        self.grid[agent_move] = -1   

#An agent class. Currently barebones
class Agent():
    def __init__(self, size, a_coords, b_coords):
        self.x, self.y = rd.randint(0, size-1), rd.randint(0, size-1)
        while ((self.x, self.y) == (a_coords or b_coords)):
            self.x, self.y = rd.randint(0, size-1), rd.randint(0, size-1)
        self.opts = ["up", "down", "left", "right"]

    def choose_best_option():
        #some sort of policy calculation
        #return: best option
        pass

    def move(self, direction):
        if direction=="left":
            return(self.x-1, self.y)
        if direction=="right":
            return(self.x+1, self.y)
        return (rd.choice([self.x+1, self.x-1]), self.y)
    
#Class to store hyperparameters
class Hypers():
    def __init__(self, eps, gamma):
        self.eps = eps
        self.gamma

    def __call__(self):
        return (self.eps, self.gamma)

##Method to initiate agent coordinates should go in setup method since both the Environment and the Agent need to know
#Or we need a hierarchy - consult w/ group

In [7]:
#demo
grid = Environment(5)
bond = Agent(5, grid.a, grid.b)
grid.set_agent_start(bond)
grid.move_agent((bond.x,bond.y))
print(grid.grid)
time.sleep(3)
#may fail since move just randomly moves it up or down by one tile which can cause index OOB errors
grid.move_agent(bond.move())
print(grid.grid)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  2.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  1.  0.  0.  2.]]
